parse_config:
  zmk_additional_includes:
    - zmk-helpers/include

  modifier_fn_map:
    left_shift: ‚áß
    left_alt: ‚å•
    right_alt: Alt
    left_ctrl: ^
    left_gui: ‚åò
    keycode_combiner: "{mods}{key}"
    mod_combiner: "{mod_1}{mod_2}"

  raw_binding_map:
    "&bt_sel 0": BT 1
    "&bt_sel 1": BT 2
    "&bt_sel 2": BT 3
    "&bt_sel 3": BT 4
    "&bt_sel 4": BT 5
    "&bt_clr 0": clear 1
    "&bt_clr 1": clear 2
    "&bt_clr 2": clear 3
    "&bt_clr 3": clear 4
    "&bt_clr 4": clear 5
    "&caps_word": caps word
    "&flash 4": flash
    "&flash 6": flash
    "&flash 7": flash
    "&ind_bat": battery status
    "&ind_con": connection status
    "&mkp LCLK": "mouse click"
    "&mkp RCLK": "right click"
    "&mmv MOVE_DOWN": mouse ‚Üì
    "&mmv MOVE_LEFT": mouse ‚Üê
    "&mmv MOVE_RIGHT": mouse ‚Üí
    "&mmv MOVE_UP": mouse ‚Üë
    "&msc SCRL_DOWN": scroll ‚Üì
    "&msc SCRL_LEFT": scroll ‚Üê
    "&msc SCRL_RIGHT": scroll ‚Üí
    "&msc SCRL_UP": scroll ‚Üë
    "&sk LSHIFT": sticky ‚áß
    "&studio_unlock": ZMK Studio
    "&tmux QMARK": keymap help
    "&tmux A": rename tab
    "&tmux C": new tab
    "&tmux D": DETACH
    "&tmux N1": tab 1
    "&tmux N2": tab 2
    "&tmux N3": tab 3
    "&tmux N4": tab 4
    "&tmux N5": tab 5
    "&tmux N6": tab 6
    "&tmux N7": tab 7
    "&tmux N8": tab 8
    "&tmux N9": tab 9
    "&tmuxldr": tmux leader
    "&usb_sel": USB
    "&vimQ": QUIT
    "&vldr W": save
    "&vldr Q": exit
    "&vtab N1": tab 1
    "&vtab N2": tab 2
    "&vtab N3": tab 3
    "&vtab N4": tab 4
    "&vtab N5": tab 5
    "&vtab N6": tab 6
    "&vtab N7": tab 7
    "&vtab N8": tab 8
    "&vtab N9": tab 9
    GC(Q): lock screen
    GCS(N4): screen copy
    GS(N4): screen shot
    HYPR(N4): launch pad

  zmk_keycode_map:
    AMPS: "&"
    AT: "@"
    BACKSLASH: \
    BSPC: ‚å´
    CAPS: Caps üîí
    CARET: ^
    COLON: ":"
    COMMA: ","
    C_NEXT: ‚è≠
    C_PP: ‚èØ
    C_PREV: ‚èÆ
    DEL: ‚å¶
    DLLR: $
    DOT: .
    DOWN: ‚Üì
    END: End
    EQUAL: "="
    ESC: Esc
    EXCL: "!"
    GLOBE: üåê
    GRAVE: "`"
    GT: ">"
    HASH: "#"
    HOME: Home
    KP_DIVIDE: /
    KP_MINUS: "-"
    KP_MULTIPLY: "*"
    KP_N0: "0"
    KP_N1: "1"
    KP_N2: "2"
    KP_N3: "3"
    KP_N4: "4"
    KP_N5: "5"
    KP_N6: "6"
    KP_N7: "7"
    KP_N8: "8"
    KP_N9: "9"
    KP_NUM: Num üîí
    KP_PLUS: +
    LALT: ‚å•
    LBKT: "["
    LBRC: "{"
    LCTL: ^
    LCTRL: ^
    LC(UP): mission control
    LEFT: ‚Üê
    LGUI: ‚åò
    LPAR: (
    LSHFT: ‚áß
    LSHIFT: sticky shift
    LT: <
    MINUS: "-"
    PG_DN: PgDn
    PG_UP: PgUp
    PIPE: "|"
    PLUS: +
    PRCNT: "%"
    QMARK: "?"
    RALT: Alt
    RBKT: "]"
    RBRC: "}"
    RET: ‚Üµ
    RIGHT: ‚Üí
    RPAR: )
    SEMI: ;
    SLASH: /
    SPC: ‚ê£
    SQT: "'"
    STAR: "*"
    TAB: ‚á•
    TILDE: "~"
    UNDER: _
    UP: ‚Üë

  zmk_combos:
    # These are all on my Charlieflex board
    combo_unlock:
      align: top
      offset: 1
    combo_b:
      dendron: true
    combo_j:
      dendron: true
    combo_less_than:
      dendron: true
    combo_greater_than:
      dendron: true
    combo_esc:
      draw_separate: true
    combo_tab:
      draw_separate: true
    combo_backspace:
      draw_separate: true
    combo_return:
      draw_separate: true
    combo_mouse_click:
      layers: [flash mode]
    combo_mouse_right_click:
      layers: [flash mode]
    combo_mouse_up:
      layers: [flash mode]
    combo_mouse_down:
      layers: [flash mode]
    combo_mouse_left:
      layers: [flash mode]
    combo_mouse_right:
      layers: [flash mode]
    combo_scroll_up:
      layers: [flash mode]
    combo_scroll_down:
      layers: [flash mode]
    combo_scroll_left:
      layers: [flash mode]
    combo_scroll_right:
      layers: [flash mode]
    combo_flash:
      dendron: true
